backtraces_path = "~/.config/neovide/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = true # platform-specific: false (Linux/macOS) or true (Windows)
tabs = true
title-hidden = false
vsync = true
wsl = false

[font]
normal = ["Hack Nerd Font"] # Will use the bundled Fira Code Nerd Font by default
size = 18.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "native"

[box-drawing.sizes]
default = [2, 4]  # Thin and thick values respectively, for all sizes
